metricbeat.modules:
  - module: system
    metricsets: [
      "core",
      "diskio",
      "fsstat",
      "load",
      "cpu",
      "filesystem",
      "memory",
      "network",
      "process"
    ]

    process.cgroups.enabled: true
    cpu_ticks: true
    enabled: true
    period: 5s
    processes: ['.*']

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://149.202.91.15:9200"]
  protocol: "http"
  template.enabled: true
  template.path: "metricbeat.template.json"
  template.overwrite: false
  index: "metricbeat-%{+yyyy.MM.dd}"

  # Optional protocol and basic auth credentials.
  username: "elastic"
  password: "changeme"

#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
